name: pull-request
on: pull_request

jobs:
  preview-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: pnpm install
        run: pnpm install
      - name: build pdf
        run: pnpm run export:pdf
      - name: upload pdf to artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: 'resume.pdf'
          path: 'resume.pdf'
