name: pull-request
on: pull_request

jobs:
  preview-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: setup mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - name: yarn install
        run: yarn install
      - name: build pdf
        run: yarn run export:pdf
      - name: upload pdf to artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: 'resume.pdf'
          path: 'resume.pdf'
