name: pull-request
on: pull_request

jobs:
  preview-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: setup mise
        uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0
      - name: yarn install
        run: yarn install
      - name: build pdf
        run: yarn run export:pdf
      - name: upload pdf to artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: 'resume.pdf'
          path: 'resume.pdf'
