name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: setup mise
        uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: yarn install
        run: yarn install
      - name: build pdf
        run: yarn run export:pdf
      - name: create release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: resume.pdf
