name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: setup mise
        uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
      - name: yarn install
        run: yarn install
      - name: build pdf
        run: yarn run export:pdf
      - name: create release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: resume.pdf
